### ISSUE TITLE
Post Info on Usage in README.md

### ISSUE THREAD

**Issue by gardotd426** [miptsu/navi_dont_sleep#1]
There's no information whatsoever on how to actually use this, I'm assuming it's installed with:
```
git clone https://github.com/miptsu/navi_dont_sleep.git
cd navi_dont_sleep
mkdir build && cd build
cmake ..
make && sudo make install
```
but there's no indication whatsoever on how to actually run the program, turn navi_dont_sleep on or off, etc.

**Comment by gardotd426** [comment]
If @miptsu doesn't add any directions to the README, you also need `vtk` installed, not just opencv, and you basically do what I suggested above:
```
git clone https://github.com/miptsu/navi_dont_sleep.git
cd navi_dont_sleep
mkdir build; cd build
cmake ..
make
```
at which point you'll have the executable in the `build/` directory. When you run it a window pops up showing a clock of how long the program has been running, I'm assuming the program is running while that window is open.

**Comment by miptsu** [comment]
Thanks for command line prompt. It is in readme now.

I have no VTK. Anyone can use OpenCV without VTK if no VTK-action is planned. So one can configure OpenCV compilation process using cmake-gui etc to remove some useless(for his project) dependencies. A lot of 'how to compile OpenCV from git source code' on the internet, let me do not copy-paste that lessons here.

**Comment by gardotd426** [comment]
People shouldn't be expected to custom-compile OpenCV just to remove vtk
just so they can run your code, at least not without it ever even being
mentioned in the README.

If someone installs OpenCV from their distributions repositories/package
manager, and follows the exact instructions on the README, they'll get the
errors I posted. The only way to get around those errors is to either have
VTK installed, or as you said to compile OpenCV from source without vtk.
None of that is mentioned anywhere. There's a difference between
"copy-pasting lessons" and giving basic directions on how to run your
software. I've never seen a project that required a custom-compiled library
not mention that it needs to be custom-compiled.

**Comment by gardotd426** [comment]
Also, it doesn't work with mesa 20.0.0 or 20.1.0, only 19.3.4. with 20.0.0
you get "fatal error: cannot open file
'/usr/lib/clc/gfx1010-amdgcn-mesa-mesa3d.bc' : No such file or directory"

It seems the "1010" version is only with mesa 19.3.4, mesa 20.0.0 has a
bunch of variations but not 1010.

**Comment by miptsu** [comment]
I am not responsible for OpenCV library. I also can not predict all possible errors arising while using this library. This is the first time I see VTK issue, and this is OpenCV issue so you'd better write to OpenCV project issue tracker. All I can say now, installing VTK is overkill, it is better to disable it in cmake (cmake-gui app) while compiling OpenCV from github source. Also I guess it is a common way for github to compile from source, so using cmake (and very convenient cmake-gui application) should not be named as 'problem' even for large and mature project as OpenCV.
Feel free to write here what do you need to be written on readme to avoid such issues (except OpenCV compile issues as I mentioned above).

**Comment by miptsu** [comment]
As for 'mesa 20.0.0 or 20.1.0, only 19.3.4' -- you need appropriate Navi driver for OpenCL support. Check AMD site for instructions. I added this to the readme, thanks.

**Comment by gardotd426** [comment]
Are you using amdgpu-pro? OpenCL still doesn't have navi support on the
open drivers

**Comment by miptsu** [comment]
Yes , amdgpu-pro-19.50-967956-ubuntu-18.04, `./amdgpu-install -y --opencl=pal` .
